#YAML EXPLANATION FILE

Name: Interceptor
Languages: Shell-Script/Php
Original Creator: Luca Garofalo (Lucksi)
Author: Lucksi
Download: git clone https://github.com/Lucksi/Interceptor
Installation: sudo ./Installer.sh
Execution: sudo ./Interceptor.sh
Platforms: Linux
Version: 1.0.1
License: GNU General Public License v3.0
